stages:
  - unittest
  - build

unittest:
  services:
    - mysql:latest
    - redis:latest

  variables:
    MYSQL_DATABASE: kaetest
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"

  stage: unittest
  image: python:3.6.6-alpine
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update
    - apk add --no-cache git openssh libffi-dev openssl-dev alpine-sdk
    - pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ pipenv
    - pipenv install --pypi-mirror https://mirrors.aliyun.com/pypi/simple/ --system --dev
  script:
    - PYTEST=1 pytest

build:
  services:
    - docker:19.03.1-dind

  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  stage: build
  image: docker:stable
  before_script:
    - docker info
  script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin $REGISTRY
    - docker build --network host -t ${REGISTRY}kaecloud/console:latest .
    - docker tag ${REGISTRY}kaecloud/console:latest ${REGISTRY}kaecloud/console:$CI_COMMIT_TAG
    - docker images
    - docker push ${REGISTRY}kaecloud/console:$CI_COMMIT_TAG
    - docker push ${REGISTRY}kaecloud/console:latest
  only:
    - tags
