"""empty message

Revision ID: 65fc0ecca1cf
Revises: 
Create Date: 2020-05-22 09:08:38.617325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fc0ecca1cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.CHAR(length=64), nullable=False),
    sa.Column('git', sa.String(length=255), nullable=False),
    sa.Column('type', sa.CHAR(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.CHAR(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_yaml',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.CHAR(length=64), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('specs_text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'name')
    )
    op.create_index(op.f('ix_app_yaml_name'), 'app_yaml', ['name'], unique=False)
    op.create_table('deploy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.CHAR(length=64), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.CHAR(length=64), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('specs_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_version_tag'), 'deploy_version', ['tag'], unique=False)
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.CHAR(length=64), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('appname', sa.CHAR(length=64), nullable=False),
    sa.Column('tag', sa.CHAR(length=64), nullable=False),
    sa.Column('cluster', sa.CHAR(length=64), nullable=False),
    sa.Column('action', console.models.base.Enum34(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_log_app_id'), 'operation_log', ['app_id'], unique=False)
    op.create_index(op.f('ix_operation_log_appname'), 'operation_log', ['appname'], unique=False)
    op.create_index(op.f('ix_operation_log_tag'), 'operation_log', ['tag'], unique=False)
    op.create_index(op.f('ix_operation_log_username'), 'operation_log', ['username'], unique=False)
    op.create_table('release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.CHAR(length=64), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.CHAR(length=255), nullable=False),
    sa.Column('build_status', sa.Boolean(), nullable=False),
    sa.Column('specs_text', sa.Text(), nullable=True),
    sa.Column('misc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'tag')
    )
    op.create_index(op.f('ix_release_tag'), 'release', ['tag'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.CHAR(length=64), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('clusters', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_role_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.CHAR(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'role_id', name='unique_group_role')
    )
    op.create_table('role_app_association',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'app_id')
    )
    op.create_table('user_role_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.CHAR(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'role_id', name='unique_user_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_binding')
    op.drop_table('role_app_association')
    op.drop_table('group_role_binding')
    op.drop_table('role')
    op.drop_index(op.f('ix_release_tag'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_operation_log_username'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_tag'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_appname'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_app_id'), table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index(op.f('ix_deploy_version_tag'), table_name='deploy_version')
    op.drop_table('deploy_version')
    op.drop_index(op.f('ix_app_yaml_name'), table_name='app_yaml')
    op.drop_table('app_yaml')
    op.drop_table('app_config')
    op.drop_table('app')
    # ### end Alembic commands ###
