"""empty message

Revision ID: b11ec42d7f23
Revises: cdc112eeed41
Create Date: 2020-06-01 04:04:31.446104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11ec42d7f23'
down_revision = 'cdc112eeed41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('subscribers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'subscribers')
    # ### end Alembic commands ###
