kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kae-pods-watcher
  name: kae-pods-watcher
  namespace: kae
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kae-pods-watcher
  template:
    metadata:
      labels:
        k8s-app: kae-pods-watcher
    spec:
      containers:
        - name: kae-pods-watcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', 'bin/run-pods-watcher']
          args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
          volumeMounts:
            - name: kae-console-secrets-vol
              mountPath: /etc/kae/secrets
            - name: kae-console-config-vol
              mountPath: /etc/kae
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "750m"
      volumes:
        - name: kae-console-secrets-vol
          secret:
            secretName: kae-console-secrets
        - name: kae-console-config-vol
          secret:
            secretName: kae-console-config
            items:
              - key: config.py
                path: config.py
      serviceAccountName: kae-console-serviceaccount
      # Comment the following tolerations if console must not be deployed on master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
